<?xml version="1.0" encoding="UTF-8"?>

<project
  xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.io7m.calino</groupId>
    <artifactId>com.io7m.calino</artifactId>
    <version>2.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>com.io7m.calino.specification</artifactId>

  <packaging>jar</packaging>
  <name>com.io7m.calino.specification</name>
  <description>Calino texture format (File format specification)</description>
  <url>https://www.io7m.com/software/calino/</url>

  <properties>
    <checkstyle.skip>true</checkstyle.skip>
    <mdep.analyze.skip>true</mdep.analyze.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.annotation.bundle</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.osgi</groupId>
      <artifactId>org.osgi.annotation.versioning</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <!-- Copy specification resources into build directory -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <executions>
          <execution>
            <id>copy-specification-resources</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/specification/</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/resources</directory>
                  <filtering>false</filtering>
                </resource>
                <resource>
                  <directory>src/main/resources-filtered</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>

          <execution>
            <id>copy-specification-rocq</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/specification</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/rocq</directory>
                  <filtering>false</filtering>
                  <includes>
                    <include>**/*.v</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>

          <execution>
            <id>copy-specification-resources-epub</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/epub/</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/resources</directory>
                  <filtering>false</filtering>
                </resource>
                <resource>
                  <directory>src/main/resources-filtered</directory>
                  <filtering>true</filtering>
                </resource>
              </resources>
            </configuration>
          </execution>

          <execution>
            <id>copy-specification-rocq-epub</id>
            <goals>
              <goal>copy-resources</goal>
            </goals>
            <phase>generate-resources</phase>
            <configuration>
              <outputDirectory>${project.build.directory}/epub/</outputDirectory>
              <resources>
                <resource>
                  <directory>src/main/rocq/Calino/</directory>
                  <filtering>false</filtering>
                  <includes>
                    <include>**/*.v</include>
                  </includes>
                </resource>
              </resources>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>excerpts</id>
            <goals>
              <goal>java</goal>
            </goals>
            <phase>package</phase>
            <configuration>
              <mainClass>com.io7m.calino.specification.Excerpts</mainClass>
              <arguments>
                <argument>${project.basedir}/src/main/rocq</argument>
                <argument>${project.basedir}/src/main/rocq/excerpts.txt</argument>
                <argument>${project.build.directory}/specification/</argument>
              </arguments>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Generate documentation in various formats. -->
      <plugin>
        <groupId>com.io7m.xstructural</groupId>
        <artifactId>com.io7m.xstructural.maven_plugin</artifactId>
        <version>${com.io7m.xstructural.version}</version>
        <executions>
          <execution>
            <id>xhtml-single</id>
            <phase>package</phase>
            <goals>
              <goal>xhtml-single</goal>
            </goals>
            <configuration>
              <sourceFile>${project.build.directory}/specification/main.xml</sourceFile>
              <outputDirectory>${project.build.directory}/specification</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>xhtml-multi</id>
            <phase>package</phase>
            <goals>
              <goal>xhtml-multi</goal>
            </goals>
            <configuration>
              <sourceFile>${project.build.directory}/specification/main.xml</sourceFile>
              <outputDirectory>${project.build.directory}/specification</outputDirectory>
            </configuration>
          </execution>
          <execution>
            <id>epub</id>
            <phase>package</phase>
            <goals>
              <goal>epub</goal>
            </goals>
            <configuration>
              <sourceFile>${project.build.directory}/specification/main.xml</sourceFile>
              <outputDirectory>${project.build.directory}</outputDirectory>
              <outputFileName>${project.artifactId}-${project.version}.epub</outputFileName>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Attach EPUB -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>attach-epub</id>
            <phase>package</phase>
            <goals>
              <goal>attach-artifact</goal>
            </goals>
            <configuration>
              <artifacts>
                <artifact>
                  <file>${project.build.directory}/${project.artifactId}-${project.version}.epub</file>
                  <type>epub</type>
                </artifact>
              </artifacts>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- Produce specification archive -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptors>
            <descriptor>src/main/assembly/specification.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <appendAssemblyId>false</appendAssemblyId>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>io.github.zlika</groupId>
        <artifactId>reproducible-build-maven-plugin</artifactId>
      </plugin>
    </plugins>
  </build>

</project>
