#!/bin/sh
#
#  Copyright © 2021 Mark Raynsford <code@io7m.com> https://www.io7m.com
#
#  Permission to use, copy, modify, and/or distribute this software for any
#  purpose with or without fee is hereby granted, provided that the above
#  copyright notice and this permission notice appear in all copies.
#
#  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
#  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
#  SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
#  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
#  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR
#  IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#

fatal()
{
  echo "calino: fatal: $1" 1>&2
  exit 1
}

if [ -z "${CALINO_HOME}" ]
then
  fatal "CALINO_HOME is not defined"
fi

if [ -z "${CALINO_JAR_NAME}" ]
then
  CALINO_JAR_NAME="calino.jar"
fi

CALINO_JAR_FILE="${CALINO_HOME}/${CALINO_JAR_NAME}"

if [ ! -z "${CALINO_JVM_OPTIONS}" ]
then
  exec java ${CALINO_JVM_OPTIONS} -jar "${CALINO_JAR_FILE}" "$@"
else
  exec java -jar "${CALINO_JAR_FILE}" "$@"
fi
